const router = require('express').Router()
const authController = require('../controllers/authController')
const verifyToken = require('../middlewares/verifyToken')

router.post('/register', authController.register)
router.post('/login', authController.login)
router.get('/get-all-auth', authController.get_all_auth)
router.get('/get-all-auth-not-own-friend', authController.get_all_auth_not_own_friend)
router.get('/get-all-auth-request-add-friend', authController.getAllRequestAddFriend)
router.post('/get-auth-byID', authController.getAuthByID)
router.post('/edit-avatar', authController.editAvatar)
router.post('/edit-cover', authController.editCover)
router.post('/edit-desc', authController.editDesc)
router.post('/edit-info-address', authController.editAddress)
router.post('/edit-info-career', authController.editCareer)
router.post('/edit-info-school', authController.editSchool)
router.post('/edit-info-hobby', authController.editHobby)
router.post('/add-friend', authController.addfriend)
router.post('/cancel-friend', authController.cancelFriend)
router.post('/accept-request-add-friend', authController.acceptRequestAddFriend)
router.post('/get-all-auth-own-friend', verifyToken, authController.get_all_auth_own_friend)

module.exports = router